# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='seguindo',
        ),
        migrations.AddField(
            model_name='perfil',
            name='seguindo',
            field=models.ManyToManyField(related_name='_perfil_seguindo_+', to='usuarios.Perfil'),
        ),
    ]
