# Generated by Django 2.1.3 on 2018-11-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil do Usuário', 'verbose_name_plural': 'Perfis'},
        ),
    ]
